---
# Default values for vpp-icmp-responder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: docker.io
org: networkservicemesh
tag: master
pullPolicy: IfNotPresent
