version: 1.0
root: "./.tests/cloud_test/"
timeout: 3600 # 1 hour total timeout
import:
  - .cloudtest/packet.yaml
  - .cloudtest/gke.yaml
  - .cloudtest/kind.yaml
  - .cloudtest/vagrant.yaml
  - .cloudtest/aws.yaml
  - .cloudtest/azure.yaml

reporting:
  junit-report: "results/junit.xml"
executions:
  - name: "Interdomain tests packet-aws"
    env:
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/logs
    tags:
      - interdomain
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - packet
      - aws
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2

  - name: "Interdomain tests gke-packet"
    env:
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/logs
    tags:
      - interdomain
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - gke
      - packet
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2

  - name: "Interdomain tests azure-gke"
    env:
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/logs
    tags:
      - interdomain
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - azure
      - gke
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2

  - name: "Interdomain tests aws-azure"
    env:
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/logs
    tags:
      - interdomain
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - aws
      - azure
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
