---
version: 1.0
root: "./.tests/cloud_test/"
timeout: 7200  # 2 hour total total timeout
import:
  - .cloudtest/packet.yaml
  - .cloudtest/gke.yaml
  - .cloudtest/kind.yaml
  - .cloudtest/vagrant.yaml
  - .cloudtest/aws.yaml
  - .cloudtest/azure.yaml

retest:  # Allow to do test re-run if some kind of failures are detected, line CNI network plugin errors.
  count: 5  # Allow 5 times to do restart
  warmup-time: 15  # Put 15 seconds warmup for cluster instance to be used again.
  allowed-retests: 2  # If cluster instance have few attempts with retest requests one after another, we need to restart cluster.
  pattern:
    - "NetworkPlugin cni failed to set up pod"    # Error in AWS dur to leak of IPs or not ability to assign them.
    - "etcdserver: request timed out, possibly due to previous leader fail"  # Error in any could, reason unknown.
    - "unable to establish connection to VPP (VPP API socket file /run/vpp/api.sock does not exist)"  # a VPP is not started, it will be re-started in general, but will cause test fail.
    - "node(s) didn't have free ports for the requested pod ports"  # Could happen for interdomain
    - "node(s) didn't match node selector"
reporting:
  junit-report: "results/junit.xml"
executions:
  - name: "Single cluster tests"
    env:
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)
    tags:
      - basic
      - recover
      - usecase
    root: ./test/integration
    timeout: 300
    cluster-count: 1
    kubernetes-env:
      - KUBECONFIG
    on_fail: |
      make k8s-delete-nsm-namespaces
  - name: "Benchmark tests"
    env:
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)
    tags:
      - bench
    root: ./test/integration
    timeout: 600
    cluster-count: 1
    cluster-selector:
      - packet
    kubernetes-env:
      - KUBECONFIG
    on_fail: |
      make k8s-delete-nsm-namespaces

  - name: "Interdomain tests packet-aws"
    env:
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)
    tags:
      - interdomain
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - packet
      - aws
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
    on_fail: |
      make k8s-delete-nsm-namespaces
  - name: "Interdomain tests gke-packet"
    env:
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)
    tags:
      - interdomain
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - gke
      - packet
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
    on_fail: |
      make k8s-delete-nsm-namespaces
  - name: "Interdomain tests azure-gke"
    env:
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)
    tags:
      - interdomain
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - azure
      - gke
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
    on_fail: |
      make k8s-delete-nsm-namespaces
  - name: "Interdomain tests aws-azure"
    env:
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)
    tags:
      - interdomain
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - aws
      - azure
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
    on_fail: |
      make k8s-delete-nsm-namespaces
  - name: "Example-helm-vpn"
    kind: shell
    timeout: 300
    env:
      - NSM_NAMESPACE=nsm-system
      - CLUSTER_RULES_PREFIX=null
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/vpn-example
      - SPIRE_ENABLED=false  # because spire is already installed
    kubernetes-env:
      - KUBECONFIG
    run: |
      make k8s-deconfig helm-install-nsm
      make helm-install-vpn
      make k8s-check
      make k8s-logs-snapshot-only-master
      make helm-delete-vpn helm-delete-nsm
      make k8s-deconfig k8s-config
      kubectl delete pods --force --grace-period 0 -n "${NSM_NAMESPACE}" --all
    on_fail: |
      kubectl get pods -n "${NSM_NAMESPACE}"
      make k8s-logs-snapshot
      make helm-delete-vpn helm-delete-nsm
      make k8s-delete-nsm-namespaces
      make k8s-deconfig k8s-config
      kubectl delete pods --force --grace-period 0 -n "${NSM_NAMESPACE}" --all

  - name: "Example-helm-icmp"
    kind: shell
    timeout: 300
    env:
      - NSM_NAMESPACE=nsm-system
      - CLUSTER_RULES_PREFIX=null
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/icmp-example
      - SPIRE_ENABLED=false  # because spire is already installed
    kubernetes-env:
      - KUBECONFIG
    run: |
      make k8s-deconfig helm-install-nsm
      make helm-install-icmp-responder
      make k8s-check
      make k8s-logs-snapshot-only-master
      make helm-delete-icmp-responder helm-delete-nsm
      make k8s-deconfig k8s-config
      kubectl delete pods --force --grace-period 0 -n "${NSM_NAMESPACE}" --all
    on_fail: |
      kubectl get pods -n "${NSM_NAMESPACE}"
      make k8s-logs-snapshot
      make helm-delete-icmp-responder helm-delete-nsm
      make k8s-delete-nsm-namespaces
      make k8s-deconfig k8s-config
      kubectl delete pods --force --grace-period 0 -n "${NSM_NAMESPACE}" --all

  - name: "Example-helm-icmp kernel-forwarder"
    kind: shell
    timeout: 300
    env:
      - FORWARDING_PLANE=kernel
      - NSM_NAMESPACE=nsm-system
      - CLUSTER_RULES_PREFIX=null
      - STORE_POD_LOGS_IN_FILES=true
      - STORE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/icmp-example
      - SPIRE_ENABLED=false  # because spire is already installed
    kubernetes-env:
      - KUBECONFIG
    run: |
      make k8s-deconfig helm-install-nsm
      make helm-install-icmp-responder
      make k8s-check
      make k8s-logs-snapshot-only-master
      make helm-delete-icmp-responder helm-delete-nsm
      make k8s-deconfig k8s-config
      kubectl delete pods --force --grace-period 0 -n "${NSM_NAMESPACE}" --all
    on_fail: |
      kubectl get pods -n "${NSM_NAMESPACE}"
      make k8s-logs-snapshot
      make helm-delete-icmp-responder helm-delete-nsm
      make k8s-delete-nsm-namespaces
      make k8s-deconfig k8s-config
      kubectl delete pods --force --grace-period 0 -n "${NSM_NAMESPACE}" --all
