version: 1.0
root: "./.tests/cloud_test/"
timeout: 3600 # 1 hour total timeout
import:
  - .cloudtest/packet.yaml
  - .cloudtest/gke.yaml
  - .cloudtest/kind.yaml
  - .cloudtest/vagrant.yaml
  - .cloudtest/aws.yaml
  - .cloudtest/azure.yaml

reporting:
  junit-report: "results/junit.xml"
executions:
  - name: "Single cluster tests"
    env:
      - WRITE_POD_LOGS_IN_FILES=true
      - WRITE_POD_LOGS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/logs
    tags:
      - basic
      - recover
      - usecase
    root: ./test/integration
    timeout: 300
    cluster-count: 1
    kubernetes-env:
      - KUBECONFIG
  - name: "Benchmark tests"
    tags:
      - bench
    root: ./test/integration
    timeout: 600
    cluster-count: 1
    cluster-selector:
      - packet
    kubernetes-env:
      - KUBECONFIG
  - name: "Example-icmp"
    kind: shell
    env:
      - NSM_NAMESPACE=default
      - CLUSTER_RULES_PREFIX=null
    kubernetes-env:
      - KUBECONFIG
    run: |
      make k8s-deconfig helm-delete-nsm helm-install-nsm
      kubectl wait --all-namespaces --timeout=300s --for condition=Ready --all pods
      make helm-install-icmp-responder
      kubectl wait --all-namespaces --timeout=300s --for condition=Ready --all pods
      make k8s-check
      make helm-delete-icmp-responder helm-delete-nsm
  - name: "Example-vpp-icmp"
    kind: shell
    env:
      - NSM_NAMESPACE=default
      - CLUSTER_RULES_PREFIX=null
    kubernetes-env:
      - KUBECONFIG
    run: |
      make k8s-deconfig helm-delete-nsm helm-install-nsm
      kubectl wait --all-namespaces --timeout=300s --for condition=Ready --all pods
      make helm-install-vpp-icmp-responder
      kubectl wait --all-namespaces --timeout=300s --for condition=Ready --all pods
      make k8s-check
      make helm-delete-vpp-icmp-responder helm-delete-nsm
  - name: "Example-vpn"
    kind: shell
    env:
      - NSM_NAMESPACE=default
      - CLUSTER_RULES_PREFIX=null
    kubernetes-env:
      - KUBECONFIG
    run: |
      make k8s-deconfig helm-delete-nsm helm-install-nsm
      kubectl wait --all-namespaces --timeout=300s --for condition=Ready --all pods
      make helm-install-vpn
      kubectl wait --all-namespaces --timeout=300s --for condition=Ready --all pods
      make k8s-check
      make helm-delete-vpn helm-delete-nsm
