sudo: required

language: go
service: 
  - docker

go:
  - "1.10.x"

go_import_path: github.com/ligato/networkservicemesh

before_script:
- sudo mount --make-rshared /

script:
- ./scripts/verify-codegen.sh
- docker build -t ligato/networkservicemesh/netmesh-test -f build/nsm/docker/Test.Dockerfile .
- docker build -t ligato/networkservicemesh/netmesh -f build/nsm/docker/Dockerfile .
- ./scripts/integration-tests minikube

notifications:
  irc:
    - "chat.freenode.net#networkservicemesh"
