language: go

go:
  - "1.10.x"

install:
  - ./scripts/install-protoc.sh

script:
- [[ "$(go fmt ./...)" == "" ]] # Check for gofmt compliance
- go get -u github.com/golang/protobuf/protoc-gen-go
- go generate ./...
- go build ./...
- go test ./...

notifications:
  irc:
    - "chat.freenode.net#networkservicemesh"
