language: go

go:
  - "1.10.x"

install:
  - ./scripts/install-protoc.sh

script:
- echo "Looking for protoc-gen-go ..." && find ~/ -name protoc-gen-go
- go get -u github.com/golang/protobuf/protoc-gen-go
- make
