language: go
service: docker

go:
  - "1.10.x"

script:
- docker build -t ligato/networkservicemesh/nsm -f build/nsm/docker/Dockerfile .

notifications:
  irc:
    - "chat.freenode.net#networkservicemesh"
