language: go
service: docker

go:
  - "1.10.x"

script:
- docker build -t ligato/networkservicemesh/netmesh-test -f build/nsm/docker/Test.Dockerfile .
- docker build -t ligato/networkservicemesh/netmesh -f build/nsm/docker/Dockerfile .

notifications:
  irc:
    - "chat.freenode.net#networkservicemesh"
