sudo: required

language: go
service: 
  - docker

go:
  - "1.10.x"

go_import_path: github.com/ligato/networkservicemesh

before_script:
- sudo mount --make-rshared /

script:
- shellcheck $(find . -name "*.sh" -not -path "./vendor/*")
- ./scripts/verify-codegen.sh
- docker build -t ligato/networkservicemesh/netmesh-test -f build/nsm/docker/Test.Dockerfile .
- docker build -t ligato/networkservicemesh/netmesh -f build/nsm/docker/Dockerfile .
- docker build -t ligato/networkservicemesh/nsm-init -f build/nsm-init/docker/Dockerfile .
- ./scripts/travis-integration-tests.sh minikube

notifications:
  irc:
    - "chat.freenode.net#networkservicemesh"
