language: go

go:
  - "1.10.x"

install:
  - ./scripts/install-protoc.sh

script:
- test -z $(go fmt ./...) || (echo "Run go fmt ./... and recommit your code";exit 1)
- go get -u github.com/golang/protobuf/protoc-gen-go
- go generate ./...
- go build ./...
- go test ./...

notifications:
  irc:
    - "chat.freenode.net#networkservicemesh"
