sudo: required

language: go
service:
  - docker

go:
  - "1.10.x"

go_import_path: github.com/ligato/networkservicemesh

before_install:
- ./.travis/update-docker.sh

before_script:
- sudo mount --make-rshared /
- sudo mount --make-rshared /sys
- sudo mount --make-rshared /var/run

script:
- make all
- ./scripts/travis-integration-tests.sh minikube

# We only want to push docker images on a push to master, not a pull request
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then make docker-push ; fi

notifications:
  irc:
    - "chat.freenode.net#networkservicemesh"

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: P3x5fQd4nasnulf51QDobnKHisjXzoFvxXvEXMeP0CP05s5Nsohr6uKAwcFVXB3ylHPx9RZ/Aiv9DuCaxl9bRhBRAcMYvJ/5KEFxkdbej7IbQ074X8Dg1d0XcPkfiNURRRNtm5C3n32NnH2+LwU6fqp7ggxHaS8H79Fpzp03thqVubUn5LBoBWjJAQipmLBFdwVbwmdP09cd/4eFsmShUxrAqYiOrVvOrJhzlp+Qb16rx2eKY8BNxNCfN6BOlXhyqwkpIDxsRpaG/rMBz45pwWLn9QsbgsJwrqW7u9YiajAadJJ7z+D8uT5UzW1JqKUByZUMSTznfVGybobn32GvcUuGIwRpe0yF/abUFdrzMCT7H8Tv2VmBS6N9KcP+XLSK5IcrwlBKh3KETGxkwgqN5ea3EAb0TUqr4LLQz1pcVXtY5W58087F38lgbGy48uMKDzCL0Zu02h5tCdH/eXT6FFp82kUFAxjuMHwAG/TVcu2n9ZthNdtmS7+mW8+VVgo/NlYr2JK8VjanBbO36uPghQAptve3DwQzh7Ww6ljM9FWZFN40KUWHA5P0tPsehHXklZTigt8zGRNN/eQ8Z+M1HsOgoXazWyn8ne0IzCX1Nd7MBGCHHsjWjf7Tu8zH22doTOzwnUslnQ2lJD3fbKMzE+k6+6q78Cr4cmcgly6vto8=
  - secure: kSmG1KqPcfJVsSymQBUl3xhxrC+B2khM6crZB6d8Ead+ZoE4alSe50tmjtfUAYzespi5PerbAppSu8N5+Rrd+eBTikuSbWSlTQh9XvRTqbLUDj0qjnrvQD96QvjgpnhfVIlUW+AHa/7fRlyortLpiynsp1T4+LjOqNh26FdYGyyxBoW/PIDm7URyKszmYMUv+7XrRv05K+RdQ95UQ7fUgtBbM+AtC+hpYHT4fiHaS1aX9PNklbZ7o9LbL0p1jWYLHWMTrr+tsR+/LTvH7Xv29u/3CzCiovpr7jD0Bn1HoWytAjs3IVJJ2WeiKW2lgkRSTDy126mRV0F2+6lT3jB81eQLByjwJ3c/5TxLg0Mxqg2gioFw5+7eXVeS8PT47a+GWpKPEEeSyeBJa8HOoETNasK30GOXdiyZ9lFZR5VZxN5NdcHWOlvRy7ZPaAj2wD9HMfV5WCJVvoQqpYrvvoexicHWXTKIgeiFXfc+shtShcvSnTRmMCcaUPZoBxv6zMiFcJK4BktXULWanGUJOCNUEAdGzq0ncA3frtIS0QFmqxpYNSU2n9VfQOpJiacm5kHVnbUHWPB7F/c4KPIF2gzigAFrVjlbAl/04Jpn7sQNFjIOqWq+e6OF9I7I7pgCg2sN0nBoVlFkf3mwlVOhcM1z4lgV017xM2ITlIha0ofSiHk=
  - secure: q2GUOyvfVXEKGp5UHKbTcvhBcR9l+UlSDfMyJXV5b+oBshJeNpilKlKhX/5P8J/eMfNz01XoNDdqgiQQPqmoRbyplOBbc9PrB6HtS89cv/vYzsbbu92+4jBuI1u9Y3GTaQzRbNGLznUQ9uj27DvFhmkQwJLhY64JV7tlddnbSXpD7W6iS7kZGTrNn6b4hhyalP0FS/endcryU5Lf8aQB5pAj0+zpRCaYqubP4wx0pu04OoWx15Okghffzulf8cVztjBW7I/sSaKI6ElrG4ua8VbiJS7HA4jacjVQMZBoQjksFVd7skZ5I2G651haZIVLlTCH+HQNRPwvpPEnepV7F498cEQGjEmmf1yhAZpE4zDkMBh6a65EYIw9AtT+hTHBkV3h7OTQRqxowjAgQosp24lhu8Pg5RkHQGHsOvpybMSKyboexusARwieuajby48fl8ixbFPKlL8km3MdOTwhFbN/M2QAUzmIKrm8RYvRsztu4jmoHpGDIVVOMvbIvB84pdj82WAjBjj7er//hE6QX/sXAlc0mF1P/9lMMsqX6LTdaBohXzva/jt3Hpds9+wC3QDez8LlDNBJgzuHOebrrr0XoWZSzuzP99WKCTHfTL2VwT6sgDYTUaFZXwSLepCvvYvnFXnf1sLPB3JGfHrXYKhSouLKe0Sn/voee/rsTWA=
