language: go

go:
  - "1.10.x"

before_install:
  - sudo apt-get install -y unzip

install:
  - ./scripts/install-protoc.sh

script:
- echo "Looking for protoc-gen-go ..." && find ~/ -name protoc-gen-go
- make
