sudo: required

language: go
service: 
  - docker

go:
  - "1.10.x"

go_import_path: github.com/ligato/networkservicemesh

before_install:
- ./.travis/update-docker.sh

before_script:
- sudo mount --make-rshared /
- sudo mount --make-rshared /sys
- sudo mount --make-rshared /var/run

script:
- make all
- ./scripts/travis-integration-tests.sh minikube

notifications:
  irc:
    - "chat.freenode.net#networkservicemesh"
