# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen"
]

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[override]]
  name = "github.com/json-iterator/go"
  # override set due to CaseSensitive option not being available in latest
  # stable version (1.1.3)
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  name = "github.com/ligato/cn-infra"
  version = "1.3.0"

[[override]]
  name = "github.com/prometheus/procfs"
  # revision is set because it is an in-development library with an evolving API
  revision = "7d6f385de8bea29190f15ba9931442a0eaef9af7"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[override]]
  name = "google.golang.org/grpc"
  version = "1.2.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/kubernetes"
  # kubernetes-1.11.0 resolves to 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  # We set the revision to work around a transitive constraint issue introduced
  # in an interaction between k8s.io/client-go and k8s.io/kubernetes
  revision = "91e7b4fd31fcd3d5f436da26c980becec37ceefe"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    go-tests = false
