---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networkservices.networkservicemesh.io
spec:
  conversion:
    strategy: None
  group: networkservicemesh.io
  names:
    kind: NetworkService
    listKind: NetworkServiceList
    plural: networkservices
    shortNames:
      - netsvc
      - netsvcs
    singular: networkservice
  scope: Cluster
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
