defaults: &defaults
  working_directory: /go/src/github.com/ligato/networkservicemesh
  docker:
    - image: circleci/golang:1.10

version: 2
jobs:
  sanity-check:
    <<: *defaults
    steps:
      - checkout
      - run: sudo apt-get install yamllint shellcheck python3-pkg-resources
      - run: yamllint -c .yamllint.yml $(git ls-files '*.yaml' '*.yml' | grep -v 'vendor/')
      - run: make check dep-check

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: go install ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
      - run: make verify docker-build

  deploy-k8s-packet:
    working_directory: /cncf
    docker:
      - image: platoff/cross-cloud
    steps:
      - run: ./ci-cluster-provision.sh packet-deploy
      - run: 
          command: kubectl create -f ./rbac/
          environment:
            KUBECONFIG: /cncf/data/kubeconfig
      - persist_to_workspace:
          root: data
          paths:
            - ./*

workflows:
  version: 2
  build-and-test:
    jobs:
      - sanity-check
      - build:
          requires:
            - sanity-check
      - deploy-k8s-packet:
          requires:
            - sanity-check
