version: 2
jobs:
  sanity-check:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get install yamllint python3-pkg-resources
            ./.circleci/install-shellcheck.sh
      - run: yamllint -c .yamllint.yml $(git ls-files '*.yaml' '*.yml' | grep -v 'vendor/')
      - run: go version
      - run: make vet check
      - run: go install k8s.io/code-generator/cmd/deepcopy-gen
      - run: go install github.com/golang/protobuf/protoc-gen-go
      - run: go get golang.org/x/tools/cmd/stringer
      - run: ./scripts/install-protoc.sh
      # - run: PATH=${PATH}:~/bin go generate ./...; git diff --exit-code || (echo "Run go generate ./... and recommit. If that doesn't work make sure you have installed via 'go install ./vendor/github.com/golang/protobuf/protoc-gen-go/'";exit 1)
      - run: go build ./...
      - run: mkdir -p ~/junit/
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export CONTAINER_TAG="${COMMIT}"
            export CONTAINER_FORCE_PULL="true"
            gotestsum --junitfile ~/junit/unit-tests.xml -- -short `go list ./... | grep -v networkservicemesh/test/`
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

    environment:
      GO111MODULE: 'on'

  build:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            go install ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
            make verify docker-build docker-push
      - run:
          when: on_fail
          name: Trigger packet-destroy
          command: |
            echo "Wait for 10 minutes to allow deploy to happen"
            typeset -i numsec=900
            typeset -i cnt=0
            while [ $cnt -lt ${numsec} ]; do
              echo -ne "Waited $cnt seconds out of $numsec\033[0K\r"
              ((cnt=cnt+1))
              sleep 1
            done
            curl --user ${CIRCLE_API_PROJECT_TOKEN}: \
                --data build_parameters[CIRCLE_JOB]=packet-destroy \
                --data build_parameters[CIRCLE_WORKFLOW_ID]=${CIRCLE_WORKFLOW_ID} \
                --data revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH


  packet-deploy:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
      - run: unzip terraform_0.11.10_linux_amd64.zip
      - run: mv terraform /go/bin/
      - run: mkdir data
      - run: ssh-keygen -t rsa -f data/sshkey -q -N ""
      - run: ssh-add data/sshkey
      - run: .circleci/provision.sh
      - run: make packet-get-kubeconfig
      - run: cp kubeconfig data/
      - run: cp -a scripts/terraform/ data/
      - run:
          when: on_fail
          command: .circleci/destroy-cluster.sh
      - save_cache:
          key: cncf-data-{{.Environment.CIRCLE_WORKFLOW_ID}}
          paths:
            - data

  packet-integration-tests:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            sudo ./.circleci/install-yq.sh
      - run:
          command: |
            ./.circleci/set-nameserver.sh sudo
            sudo apt-get install gettext-base
      - run:
          command: |
            sudo mkdir -p /cncf/data
            sudo chown -R circleci:circleci /cncf/
          name: Cache Prep
      - restore_cache:
          key: cncf-data-{{.Environment.CIRCLE_WORKFLOW_ID}}
      - run:
          command: |
            ./scripts/prepare-circle-integration-tests.sh
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export CONTAINER_TAG="${COMMIT}"
            export CONTAINER_FORCE_PULL="true"
            mkdir -p ~/junit/
            gotestsum --junitfile ~/junit/integration-tests.xml ./test/... -timeout 30m
          no_output_timeout: 30m
          environment:
            KUBECONFIG: /home/circleci/project/data/kubeconfig
            GO111MODULE: 'on'
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - run:
          when: always
          name: Dump K8s state
          command: |
            kubectl get nodes
            kubectl get pods -o wide
            kubectl describe pods
          environment:
            KUBECONFIG: /home/circleci/project/data/kubeconfig
      - run:
          when: on_fail
          name: Trigger packet-destroy
          command: |
            curl --user ${CIRCLE_API_PROJECT_TOKEN}: \
                --data build_parameters[CIRCLE_JOB]=packet-destroy \
                --data build_parameters[CIRCLE_WORKFLOW_ID]=${CIRCLE_WORKFLOW_ID} \
                --data revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH

  packet-destroy:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          command: |
            sudo mkdir -p /cncf/data
            sudo chown -R circleci:circleci /cncf/
          name: Cache Prep
      - restore_cache:
          key: cncf-data-{{.Environment.CIRCLE_WORKFLOW_ID}}
      - run: wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
      - run: unzip terraform_0.11.10_linux_amd64.zip
      - run: mv terraform /go/bin/
      - run: cp -a data/terraform/* ./scripts/terraform/
      - run: cd ./scripts/terraform && terraform init && cd ../..
      - run: .circleci/destroy-cluster.sh

  build-nsmd:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            make docker-nsmd-build
            make docker-nsmd-push
  build-nsmd-k8s:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            make docker-nsmd-k8s-build
            make docker-nsmd-k8s-push
  build-nsmdp:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            make docker-nsmdp-build
            make docker-nsmdp-push
  build-admission-webhook:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export BUILD_TAG="circle-${CIRCLE_BUILD_NUM}"
            export TAG="$BUILD_TAG"
            make docker-admission-webhook-build
            make docker-admission-webhook-push
  build-crossconnect-monitor:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            make docker-crossconnect-monitor-build
            make docker-crossconnect-monitor-push
  build-icmp-responder-nse:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            make docker-icmp-responder-nse-build
            make docker-icmp-responder-nse-push

  build-vppagent-icmp-responder-nse:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            make docker-vppagent-icmp-responder-nse-build
            make docker-vppagent-icmp-responder-nse-push
  build-vppagent-nsc:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            make docker-vppagent-nsc-build
            make docker-vppagent-nsc-push
  build-nsc:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            make docker-nsc-build
            make docker-nsc-push
  build-vppagent-dataplane:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            make docker-vppagent-dataplane-build
            make docker-vppagent-dataplane-push
  build-vppagent-firewall-nse:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            make docker-vppagent-firewall-nse-build
            make docker-vppagent-firewall-nse-push
  docker-push-latest:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export PULL_TAG="${COMMIT}"
            export TAG="latest"
            export REPO="networkservicemesh"
            export CONTAINERS=(nsmd nsmd-k8s nsmdp crossconnect-monitor icmp-responder-nse vppagent-icmp-responder-nse vppagent-nsc nsc vppagent-dataplane)
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            for c in ${CONTAINERS[@]}; do
              docker pull ${REPO}/${c}:${PULL_TAG}
              docker tag ${REPO}/${c}:${PULL_TAG} ${REPO}/${c}:${TAG}
              docker push ${REPO}/${c}:${TAG}
            done

workflows:
  version: 2
  build-and-test:
    jobs:
      - sanity-check
      - build-nsmd:
          requires:
            - sanity-check
      - build-nsmd-k8s:
          requires:
            - sanity-check
      - build-admission-webhook:
          requires:
            - sanity-check
      - build-crossconnect-monitor:
          requires:
            - sanity-check
      - build-nsmdp:
          requires:
            - sanity-check
      - build-icmp-responder-nse:
          requires:
            - sanity-check
      - build-vppagent-icmp-responder-nse:
          requires:
            - sanity-check
      - build-vppagent-nsc:
          requires:
            - sanity-check
      - build-nsc:
          requires:
            - sanity-check
      - build-vppagent-dataplane:
          requires:
            - sanity-check
      - build-vppagent-firewall-nse:
          requires:
            - sanity-check
      - packet-deploy:
          requires:
            - sanity-check
      - packet-integration-tests:
          requires:
            - build-nsmd
            - build-nsmd-k8s
            - build-nsmdp
            - build-crossconnect-monitor
            - build-icmp-responder-nse
            - build-vppagent-icmp-responder-nse
            - build-vppagent-nsc
            - build-nsc
            - build-vppagent-firewall-nse
            - packet-deploy
      - packet-destroy:
          requires:
            - packet-integration-tests
      - docker-push-latest:
          requires:
            - packet-destroy
          filters:
            branches:
              only: master
