---
version: 2.1

jobs:
  sanity-check:
    resource_class: medium+
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get install yamllint python3-pkg-resources
            ./.circleci/install-shellcheck.sh
      - run: yamllint -c .yamllint.yml $(git ls-files '*.yaml' '*.yml')
      - run: go version
      - run:
          name: Download Go Dependencies
          command: |
            attempt=1
            until go mod download || (( $attempt >= 10 )); do attempt=$(( $attempt + 1 )); echo "Trying again, attempt $attempt"; done
      - run: "! go fmt ./... 2>&1 | read"
      - run:
          name: golint
          command: |
            go get golang.org/x/lint/golint
            golint ./...
      - run: make vet check
      - run: go install k8s.io/code-generator/cmd/deepcopy-gen
      - run: go install github.com/golang/protobuf/protoc-gen-go
      - run: go get golang.org/x/tools/cmd/stringer
      - run: ./scripts/install-protoc.sh
      # - run: go generate ./...
      - run: go build ./...
      - run: mkdir -p ~/junit/
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export CONTAINER_TAG="${COMMIT}"
            export CONTAINER_FORCE_PULL="true"
            gotestsum --junitfile ~/junit/unit-tests.xml -- -short `go list ./... | grep -v networkservicemesh/test/`
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
    environment:
      GO111MODULE: "on"

  packet-deploy:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: wget https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      - run: unzip terraform_0.11.13_linux_amd64.zip
      - run: mv terraform /go/bin/
      - run: mkdir terraform
      - run: ssh-keygen -t rsa -f terraform/sshkey -q -N ""
      - run: ssh-add terraform/sshkey
      - run: .circleci/provision.sh
      - run: cp -a scripts/terraform/ terraform/
      - run:
          when: on_fail
          command: .circleci/destroy-cluster.sh
      - save_cache:
          key: terraform-{{.Environment.CIRCLE_WORKFLOW_ID}}
          paths:
            - /go/bin/terraform
            - terraform

  packet-deploy-k8s:
    parameters:
      cluster_id:
        type: string
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: mkdir terraform
      - restore_cache:
          key: terraform-{{.Environment.CIRCLE_WORKFLOW_ID}}
      - run: ssh-add terraform/sshkey
      - run: cp -a terraform/terraform/* ./scripts/terraform/
      - run: cd ./scripts/terraform && terraform init && cd ../..
      - run: cd scripts/terraform && ./create-kubernetes-cluster.sh && cd ../..
      - run: make packet-get-kubeconfig
      - run:
          name: "Prepare cache data<< parameters.cluster_id >>"
          command: |
            mkdir -p data
            cp kubeconfig data/
      - run:
          when: on_fail
          command: .circleci/destroy-cluster.sh
      - save_cache:
          key: cncf-data-packet-<< parameters.cluster_id >>-{{.Environment.CIRCLE_WORKFLOW_ID}}
          paths:
            - data
    environment:
      PACKET_CLUSTER_ID: "<< parameters.cluster_id >>"

  integration-tests:
    parameters:
      cloud_provider:
        type: string
      cluster_id:
        type: string
      test_tags:
        type: string
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            sudo ./.circleci/install-yq.sh
      - run:
          command: |
            ./.circleci/set-nameserver.sh sudo
            sudo apt-get install gettext-base
      - run:
          name: Cache Prep
          command: |
            mkdir terraform
            sudo mkdir -p /cncf/data
            sudo chown -R circleci:circleci /cncf/
      - restore_cache:
          key: terraform-{{.Environment.CIRCLE_WORKFLOW_ID}}
      - run: cp -a /home/circleci/project/terraform/terraform/* ./scripts/terraform/
      - run: ssh-add /home/circleci/project/terraform/sshkey
      - restore_cache:
          key: cncf-data-<< parameters.cloud_provider >>-<< parameters.cluster_id >>-{{.Environment.CIRCLE_WORKFLOW_ID}}
      - run: cp /home/circleci/project/terraform/sshkey* /cncf/data
      - run:
          name: Downloading go deps
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export CONTAINER_TAG="${COMMIT}"
            # export CONTAINER_FORCE_PULL="true"
            ./scripts/prepare-circle-integration-tests.sh
            mkdir -p ~/junit/
            go mod download
          no_output_timeout: 40m
      - run:
          name: Running integration tests - <<parameters.test_tags>>
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export CONTAINER_TAG="${COMMIT}"
            gotestsum --junitfile ~/junit/integration-tests-basic.xml -f standard-verbose ./test/... -timeout 30m -failfast -tags="<<parameters.test_tags>>"
          no_output_timeout: 40m
      - run:
          when: always
          name: Save postmortem data
          command: |
            make << parameters.cloud_provider >>-download-postmortem
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/postmortem
      - run:
          when: always
          name: Dump K8s state
          command: |
            kubectl get nodes
            kubectl get pods -o wide
            kubectl describe pods
      - run:
          when: on_fail
          command: .circleci/cleanup-<< parameters.cloud_provider >>.sh

    environment:
      PACKET_CLUSTER_ID: "<< parameters.cluster_id >>"
      KUBECONFIG: /home/circleci/project/data/kubeconfig
      GO111MODULE: "on"

  packet-destroy:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - restore_cache:
          key: terraform-{{.Environment.CIRCLE_WORKFLOW_ID}}
      - run: cp -a /home/circleci/project/terraform/terraform/* ./scripts/terraform/
      - run: cd ./scripts/terraform && terraform init && cd ../..
      - run: .circleci/destroy-cluster.sh

  build-container:
    parameters:
      container:
        type: string
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            make docker-<< parameters.container >>-build
            make docker-<< parameters.container >>-push

  docker-push-latest:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export PULL_TAG="${COMMIT}"
            export TAG="latest"
            export REPO="networkservicemesh"
            export CONTAINERS=(nsmd nsmd-k8s nsmdp crossconnect-monitor icmp-responder-nse vppagent-icmp-responder-nse vppagent-nsc nsc vppagent-dataplane vppagent-dataplane-dev admission-webhook)
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            for c in ${CONTAINERS[@]}; do
              docker pull ${REPO}/${c}:${PULL_TAG}
              docker tag ${REPO}/${c}:${PULL_TAG} ${REPO}/${c}:${TAG}
              docker push ${REPO}/${c}:${TAG}
            done

workflows:
  version: 2
  build-and-test:
    jobs:
      - sanity-check
      - build-container:
          name: "build-nsmd"
          container: "nsmd"
          requires:
            - sanity-check
      - build-container:
          name: "build-nsmd-k8s"
          container: "nsmd-k8s"
          requires:
            - sanity-check
      - build-container:
          name: "build-nsmdp"
          container: "nsmdp"
          requires:
            - sanity-check
      - build-container:
          name: "build-admission-webhook"
          container: "admission-webhook"
          requires:
            - sanity-check
      - build-container:
          name: "build-crossconnect-monitor"
          container: "crossconnect-monitor"
          requires:
            - sanity-check
      - build-container:
          name: "build-icmp-responder-nse"
          container: "icmp-responder-nse"
          requires:
            - sanity-check
      - build-container:
          name: "build-vppagent-icmp-responder-nse"
          container: "vppagent-icmp-responder-nse"
          requires:
            - sanity-check
      - build-container:
          name: "build-vppagent-nsc"
          container: "vppagent-nsc"
          requires:
            - sanity-check
      - build-container:
          name: "build-nsc"
          container: "nsc"
          requires:
            - sanity-check
      - build-container:
          name: "build-vppagent-dataplane"
          container: "vppagent-dataplane"
          requires:
            - sanity-check
      - build-container:
          name: "build-vppagent-dataplane-dev"
          container: "vppagent-dataplane-dev"
          requires:
            - sanity-check
      - build-container:
          name: "build-vppagent-firewall-nse"
          container: "vppagent-firewall-nse"
          requires:
            - sanity-check
      - packet-deploy:
          requires:
            - sanity-check
      - packet-deploy-k8s:
          name: "packet-deploy-k8s-1"
          cluster_id: "1"
          requires:
            - packet-deploy
      - packet-deploy-k8s:
          name: "packet-deploy-k8s-2"
          cluster_id: "2"
          requires:
            - packet-deploy
      - integration-tests:
          name: "packet-test-basic-usecase"
          cloud_provider: "packet"
          cluster_id: "1"
          test_tags: "basic usecase"
          requires:
            - packet-deploy-k8s-1
      - integration-tests:
          name: "packet-test-recover"
          cloud_provider: "packet"
          cluster_id: "2"
          test_tags: "recover"
          requires:
            - packet-deploy-k8s-2
      - packet-destroy:
          requires:
            - "packet-test-basic-usecase"
            - "packet-test-recover"
      - docker-push-latest:
          requires:
            - packet-destroy
          filters:
            branches:
              only: master
