version: 2
jobs:
  sanity-check:
    working_directory: /go/src/github.com/ligato/networkservicemesh
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get install yamllint python3-pkg-resources
            ./.circleci/install-shellcheck.sh
      - run: yamllint -c .yamllint.yml $(git ls-files '*.yaml' '*.yml' | grep -v 'vendor/')
      - run: make check dep-check verify

  build:
    working_directory: /go/src/github.com/ligato/networkservicemesh
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export BUILD_TAG="circle-${CIRCLE_BUILD_NUM}"
            export TAG="$BUILD_TAG"
            go install ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
            make verify docker-build docker-push

  packet-deploy:
    working_directory: /cncf
    docker:
      - image: registry.cncf.ci/cncf/cross-cloud/provisioning:production
    steps:
      - checkout:
          path:
            nsm
      - run: nsm/.circleci/set-nameserver.sh
      - run: nsm/.circleci/provision.sh packet-deploy
      - run:
          when: on_fail
          command: nsm/.circleci/provision.sh packet-destroy
      - run:
          command: kubectl create -f /cncf/rbac/
          environment:
            KUBECONFIG: /cncf/data/kubeconfig
      - persist_to_workspace:
          root: /cncf/data
          paths:
            - ./*

  packet-integration-tests:
    working_directory: /go/src/github.com/ligato/networkservicemesh
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./.circleci/set-nameserver.sh sudo
            sudo apt-get install gettext-base
      - attach_workspace:
          at: ./data
      - run:
          command: ./scripts/circle-integration-tests.sh
          environment:
            KUBECONFIG: /go/src/github.com/ligato/networkservicemesh/data/kubeconfig
      - run:
          when: always
          command: ./.circleci/destroy-cluster.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - sanity-check
      - build:
          requires:
            - sanity-check
      - packet-deploy:
          requires:
            - sanity-check
      - packet-integration-tests:
          requires:
            - build
            - packet-deploy
