version: 2
jobs:
  sanity-check:
    working_directory: /go/src/github.com/ligato/networkservicemesh
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: sudo apt-get install yamllint shellcheck python3-pkg-resources
      - run: yamllint -c .yamllint.yml $(git ls-files '*.yaml' '*.yml' | grep -v 'vendor/')
      - run: make check dep-check

  build:
    working_directory: /go/src/github.com/ligato/networkservicemesh
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - setup_remote_docker
      - run: go install ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
      - run:
          command: |
            echo 'COMMIT="${CIRCLE_SHA1:8:8}"' >> $BASH_ENV
            echo 'BUILD_TAG="circle-${CIRCLE_BUILD_NUM}"' >> $BASH_ENV
            echo 'TAG="$BUILD_TAG"' >> $BASH_ENV
            echo 'COMMIT="$COMMIT"'
            echo 'BUILD_TAG="$BUILD_TAG"'
      - run: make verify docker-build docker-push

  packet-deploy:
    working_directory: /cncf
    docker:
      - image: registry.cncf.ci/cncf/cross-cloud/provisioning:production
    steps:
      - checkout:
          path:
            nsm
      - run: nsm/scripts/circle-set-nameserver.sh
      - run: nsm/scripts/circle-provision.sh packet-deploy
      - run:
          when: on_fail
          command: nsm/scripts/circle-provision.sh packet-destroy
      - run:
          command: kubectl create -f /cncf/rbac/
          environment:
            KUBECONFIG: /cncf/data/kubeconfig
      - persist_to_workspace:
          root: /cncf/data
          paths:
            - ./*

  packet-integration-tests:
    working_directory: /go/src/github.com/ligato/networkservicemesh
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: ./scripts/circle-set-nameserver.sh sudo
      - attach_workspace:
          at: ./data
      - run:
          command: ./scripts/circle-integration-tests.sh
          environment:
            KUBECONFIG: /go/src/github.com/ligato/networkservicemesh/data/kubeconfig
      - run:
          when: always
          command: |
            cd /cncf
            ./circleci-provision.sh packet-destroy

workflows:
  version: 2
  build-and-test:
    jobs:
      - sanity-check
      - build:
          requires:
            - sanity-check
      - packet-deploy:
          requires:
            - sanity-check
      - packet-integration-tests:
          requires:
            - build
            - packet-deploy
