apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: networkservice
spec:
  template:
    metadata:
      labels:
        app: networkservice-ds
    spec:
      nodeSelector:
        app: networkservice-node
      containers:
        - name: netmesh
          image: ligato/networkservicemesh/netmesh
          imagePullPolicy: Never
