---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: networkservice
spec:
  template:
    metadata:
      labels:
        app: networkservice-ds
    spec:
      serviceAccountName: networkservicemesh
      containers:
        - name: netmesh
          image: networkservicemesh/netmesh:${TAG}
          imagePullPolicy: IfNotPresent
          env:
            - name: NSM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NSM_IPADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: kubelet-socket
              mountPath: /var/lib/kubelet/device-plugins
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
      volumes:
        - hostPath:
            path: /var/lib/kubelet/device-plugins
            type: DirectoryOrCreate
          name: kubelet-socket
        - hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
          name: nsm-socket

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: networkservicemesh

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crd-creater
rules:
  - apiGroups: ["networkservicemesh.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["thirdpartyresources", "thirdpartyresources.extensions"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crd-creater-binding
subjects:
  - kind: ServiceAccount
    namespace: default
    name: networkservicemesh
roleRef:
  kind: ClusterRole
  name: crd-creater
  apiGroup: rbac.authorization.k8s.io
