---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nse-memif
  name: nse-memif
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: nse-memif
  name: nse-memif
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: nse-memif
  name: nse-memif
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nse-memif
subjects:
  - kind: ServiceAccount
    name: nse-memif
---
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io: "true"
        networkservicemesh.io/app: "nse"
    spec:
      serviceAccount: nse-memif
      containers:
        - name: nse-memif
          image: networkservicemesh/nse-memif
          imagePullPolicy: IfNotPresent
          env:
            - name: INIT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: connect-socket
              mountPath: /var/lib/networkservicemesh
      volumes:
        - hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
          name: connect-socket
metadata:
  name: nse-memif
  namespace: default
