apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nse
  name: nse
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: nse
  name: nse
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: nse
  name: nse
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nse
subjects:
- kind: ServiceAccount
  name: nse
---
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nse-1
    spec:
      serviceAccount: nse
      containers:
        - name: nse-1
          image: ligato/networkservicemesh/nse:latest
          imagePullPolicy: IfNotPresent
          args:
          - --nsm-socket=/var/lib/networkservicemesh/nsm.ligato.io.sock
          resources:
            limits:
              nsm.ligato.io/socket: 1
          env:
          - name: INIT_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      volumes:
      - hostPath:
          path: /var/lib/networkservicemesh
          type: DirectoryOrCreate
        name: nsm-socket
metadata:
   name: nse-1
   namespace: default