apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nse-1
    spec:
      containers:
        - name: nse-1
          image: ligato/networkservicemesh/nse:latest
          imagePullPolicy: IfNotPresent
          args:
          - --nsm-socket=/var/lib/networkservicemesh/nsm.ligato.io.sock
          resources:
            limits:
              nsm.ligato.io/socket: 1
      volumes:
      - hostPath:
          path: /var/lib/networkservicemesh
          type: DirectoryOrCreate
        name: nsm-socket
metadata:
   name: nse-1
   namespace: default