# Default values for spire.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# workaround since Azure doesn't support by default 10250 security port for kubelet
azure: false
