---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
      - name: sidecar-alpine
        image: prateekgogia/alpine-net:latest
        imagePullPolicy: IfNotPresent
        command: ["sleep", "3600000"]
