---
apiVersion: networkservicemesh.io/v1
kind: NetworkService
metadata:
  name: icmp-responder
spec:
  payload: IP
  matches:
    - match:
      sourceSelector:
        app: icmp
      route:
        - destination:
          destinationSelector:
            app: icmp-responder
    - match:
      sourceSelector:
        impl: kernel
      route:
        - destination:
          destinationSelector:
            impl: kernel
