---
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "vpn-gateway-nsc"
        networkservicemesh.io/impl: "secure-intranet-connectivity"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: alpine-img
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: ['tail', '-f', '/dev/null']
      initContainers:
        - name: nsc
          image: networkservicemesh/nsc:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OUTGOING_NSC_NAME
              value: "secure-intranet-connectivity"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: vpn-gateway-nsc
  namespace: default
