apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-server
  namespace: default
  labels:
    app: spire-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  serviceName: spire-server
  template:
    metadata:
      namespace: default
      labels:
        app: spire-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube-master
      serviceAccountName: default
      containers:

        - name: spire-server
          image: gcr.io/spiffe-io/spire-server:0.7.3
          args: ["-config", "/run/spire/config/server.conf"]
          securityContext:
            privileged: true
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-secrets
              mountPath: /run/spire/secrets
              readOnly: true
            - name: spire-data
              mountPath: /run/spire/data
              readOnly: false
            - name: k8s-sa-cert
              mountPath: /run/k8s-certs/sa.pub
              readOnly: true
            - name: shared-data
              mountPath: /tmp
          livenessProbe:
            tcpSocket:
              port: 8081
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3

        - name: entry-registration
          image: networkservicemesh/spire-registration
          imagePullPolicy: IfNotPresent
          #        command: ['/opt/spire/bin/spire-server', 'entry', 'show']
  #        command: ['ls', '-la', '/tmp']
          volumeMounts:
            - name: shared-data
              mountPath: /tmp

      volumes:
        - name: spire-config
          configMap:
            name: spire-server
        - name: spire-secrets
          secret:
            secretName: spire-server
        - name: k8s-sa-cert
          hostPath:
            # NOTE: Change to the kube-apiserver's service account certificate
            path: /etc/kubernetes/pki/sa.pub
            type: File
        - name: spire-data
          hostPath:
            path: /var/spire-data
            type: DirectoryOrCreate
        - name: shared-data
          emptyDir: {}
#  volumeClaimTemplates:
#  - metadata:
#      name: spire-data
#      namespace: spire
#    spec:
#      accessModes:
#      - ReadWriteOnce
